language: android
jdk: oraclejdk8
android:
  components:
  - build-tools-22.0.1
  - android-22
before_install:
- openssl aes-256-cbc -K $encrypted_8bf9e2e639dc_key -iv $encrypted_8bf9e2e639dc_iv
  -in quexten.keystore.enc -out quexten.keystore -d
- openssl aes-256-cbc -K $encrypted_8bf9e2e639dc_key -iv $encrypted_8bf9e2e639dc_iv
  -in google-play-api.json.enc -out google-play-api.json -d
- chmod +x gradlew
