language: android
jdk:
 - oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.3
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
before_install:
- openssl aes-256-cbc -K $encrypted_8bf9e2e639dc_key -iv $encrypted_8bf9e2e639dc_iv 
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod +x gradlew
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/4c6fd7e38b48e8eeb0b3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
deploy:
  provider: script
  script: ./gradlew publishApkRelease
  on:
    tags: true
